export const FETCH_BOOKS_REQUEST = "FETCH_BOOKS_REQUEST";
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";

export const FETCH_BOOK_REQUEST = "FETCH_BOOK_REQUEST";
export const FETCH_BOOK_SUCCESS = "FETCH_BOOK_SUCCESS";

export const SAVE_SEARCH_OPTIONS = "SAVE_SEARCH_OPTIONS";

export const FETCH_MORE_BOOKS_SUCCESS = "FETCH_MORE_BOOKS_SUCCESS";

export const INCREASE_INDEX_SUCCESS = "INCREASE_INDEX_SUCCESS";

export const FETCH_FAILURE = "FETCH_FAILURE";
